import { useState, useEffect } from 'react';
import { useAuth } from '../context/AuthContext';
import { reportService, type GeneratedReportSnapshot } from '../services/reportService';
import { checkpointService } from '../services/checkpointService';
import api from '../services/api';
import { DonutChart, ChartLabels } from '../components/Charts';
import { StatusBadge } from '../components/StatusBadge';
import {
  FileBarChart, Download, Filter, Loader2, AlertCircle, X,
  User, MapPin, ArrowRight, ArrowLeft, CheckCircle2, XCircle, Clock,
  Fingerprint, ScanEye, Shield, ShieldAlert, AlertTriangle, Building,
  FilePlus2,
} from 'lucide-react';

type Direction = 'ENTRY' | 'EXIT' | 'all';
type Decision = 'VERIFIED' | 'PENDING_SUPERVISOR_REVIEW' | 'REJECTED' | 'all';
type AlertStatus = 'NONE' | 'WARNING' | 'CRITICAL' | 'all';

/** Normalized row shape shared by the live table, saved snapshots and the CSV export. */
interface ReportRow {
  verificationId: number;
  timestamp: string;
  direction: string;
  fingerprintScore: number;
  irisScore: number;
  finalScore: number;
  threshold: number;
  finalDecision: string;
  alertStatusAtVerification: string;
  alertReasonAtVerification: string | null;
  checkpointName: string | null;
  officerName: string | null;
  travelerName: string | null;
  travelerFan: string | null;
  manualReviewStatus: string | null;
  supervisorDecision: string | null;
}

/** Map a live detailed-record (backend include shape) into the normalized row shape. */
function toReportRow(r: any): ReportRow {
  return {
    verificationId: r.id,
    timestamp: r.timestamp,
    direction: r.direction,
    fingerprintScore: r.fingerprintScore,
    irisScore: r.irisScore,
    finalScore: r.finalScore,
    threshold: r.threshold,
    finalDecision: r.finalDecision,
    alertStatusAtVerification: r.alertStatusAtVerification || 'NONE',
    alertReasonAtVerification: r.alertReasonAtVerification ?? null,
    checkpointName: r.checkpoint?.name ?? null,
    officerName: r.officer?.name ?? null,
    travelerName: r.traveler?.fullName ?? null,
    travelerFan: r.traveler?.fan ?? null,
    manualReviewStatus: r.manualReviewRequest?.status ?? null,
    supervisorDecision: r.manualReviewRequest?.decision ?? null,
  };
}

/** Map a stored snapshot record into the normalized row shape. */
function snapshotToRow(r: NonNullable<GeneratedReportSnapshot['recordsData']>[number]): ReportRow {
  return {
    verificationId: r.verificationId,
    timestamp: r.timestamp,
    direction: r.direction,
    fingerprintScore: r.fingerprintScore,
    irisScore: r.irisScore,
    finalScore: r.finalScore,
    threshold: r.threshold,
    finalDecision: r.finalDecision,
    alertStatusAtVerification: r.alertStatusAtVerification || 'NONE',
    alertReasonAtVerification: r.alertReasonAtVerification ?? null,
    checkpointName: r.checkpointName ?? null,
    officerName: r.officerName ?? null,
    travelerName: r.travelerName ?? null,
    travelerFan: r.travelerFan ?? null,
    manualReviewStatus: r.manualReview?.status ?? null,
    supervisorDecision: r.manualReview?.decision ?? null,
  };
}

interface CsvMeta {
  reportTitle: string;
  generatedBy: string;
  generatedAt: string;
  periodFrom: string;
  periodTo: string;
  filterLabels: {
    officer: string;
    checkpoint: string;
    direction: string;
    decision: string;
    watchlistStatus: string;
  };
  statistics: {
    totalCrossings: number;
    verified: number;
    rejected: number;
    pendingReview: number;
    entries: number;
    exits: number;
    manualReviews: number;
    watchlistWarnings: number;
    watchlistCritical: number;
  };
  chartData?: {
    decisions: { verified: number; pending: number; rejected: number };
    directionBreakdown: { entry: number; exit: number };
    watchlistBreakdown?: { none: number; warning: number; critical: number };
    byCheckpoint: Array<{ name: string; count: number }>;
  } | null;
  records: ReportRow[];
}

/**
 * Build the full professional CSV document:
 * system header → report metadata → filters → summary statistics → chart
 * breakdowns → detailed verification records. Sections are separated by blank
 * lines so the file stays readable in Excel/Google Sheets.
 */
function buildReportCsv(meta: CsvMeta): string {
  const q = (v: unknown) => `"${String(v ?? '').replace(/"/g, '""')}"`;
  const lines: string[] = [];

  lines.push(q('INTELLIGENT AUTOMATED BORDER CONTROL SYSTEM'));
  lines.push('');
  lines.push('REPORT INFORMATION');
  lines.push(`Report Title,${q(meta.reportTitle)}`);
  lines.push(`Generated By,${q(meta.generatedBy)}`);
  lines.push(`Generated Date,${q(meta.generatedAt)}`);
  lines.push(`Report Period,${q(`${meta.periodFrom} - ${meta.periodTo}`)}`);
  lines.push('');
  lines.push('APPLIED FILTERS');
  lines.push(`Officer,${q(meta.filterLabels.officer)}`);
  lines.push(`Checkpoint,${q(meta.filterLabels.checkpoint)}`);
  lines.push(`Direction,${q(meta.filterLabels.direction)}`);
  lines.push(`Decision,${q(meta.filterLabels.decision)}`);
  lines.push(`Watchlist Status,${q(meta.filterLabels.watchlistStatus)}`);
  lines.push('');
  lines.push('SUMMARY STATISTICS');
  lines.push(`Total Crossings,${meta.statistics.totalCrossings}`);
  lines.push(`Verified,${meta.statistics.verified}`);
  lines.push(`Rejected,${meta.statistics.rejected}`);
  lines.push(`Pending Supervisor Review,${meta.statistics.pendingReview}`);
  lines.push(`Manual Reviews,${meta.statistics.manualReviews}`);
  lines.push(`Entries,${meta.statistics.entries}`);
  lines.push(`Exits,${meta.statistics.exits}`);
  lines.push(`Watchlist Warnings,${meta.statistics.watchlistWarnings}`);
  lines.push(`Watchlist Critical,${meta.statistics.watchlistCritical}`);

  if (meta.chartData) {
    lines.push('');
    lines.push('VERIFICATION RESULTS');
    lines.push(`Verified,${meta.chartData.decisions.verified}`);
    lines.push(`Pending Supervisor Review,${meta.chartData.decisions.pending}`);
    lines.push(`Rejected,${meta.chartData.decisions.rejected}`);
    lines.push('');
    lines.push('ENTRY VS EXIT');
    lines.push(`Entry,${meta.chartData.directionBreakdown.entry}`);
    lines.push(`Exit,${meta.chartData.directionBreakdown.exit}`);
    const wb = meta.chartData.watchlistBreakdown;
    if (wb) {
      lines.push('');
      lines.push('WATCHLIST STATUS');
      lines.push(`NONE,${wb.none}`);
      lines.push(`WARNING,${wb.warning}`);
      lines.push(`CRITICAL,${wb.critical}`);
    }
    if (meta.chartData.byCheckpoint.length > 0) {
      lines.push('');
      lines.push('CROSSINGS BY CHECKPOINT');
      meta.chartData.byCheckpoint.forEach((cp) => lines.push(`${q(cp.name)},${cp.count}`));
    }
  }

  lines.push('');
  lines.push('DETAILED VERIFICATION RECORDS');
  const headers = [
    'Date/Time', 'Traveller Name', 'FAN/Fayda ID', 'Officer', 'Checkpoint', 'Direction',
    'Fingerprint Score', 'Iris Score', 'Final Score', 'Threshold Used',
    'Watchlist Status', 'Alert Reason', 'Decision', 'Manual Review Status', 'Supervisor Decision',
  ];
  lines.push(headers.join(','));
  meta.records.forEach((r) => {
    const row = [
      new Date(r.timestamp).toLocaleString(),
      r.travelerName ?? '-',
      r.travelerFan ?? '-',
      r.officerName ?? '-',
      r.checkpointName ?? '-',
      r.direction,
      r.fingerprintScore != null ? Number(r.fingerprintScore).toFixed(2) : '-',
      r.irisScore != null ? Number(r.irisScore).toFixed(2) : '-',
      r.finalScore != null ? Number(r.finalScore).toFixed(2) : '-',
      r.threshold != null ? `${r.threshold}%` : '-',
      r.alertStatusAtVerification || 'NONE',
      r.alertReasonAtVerification || '-',
      r.finalDecision,
      r.manualReviewStatus ?? 'None',
      r.supervisorDecision ?? '-',
    ];
    lines.push(row.map(q).join(','));
  });

  return lines.join('\n');
}

/** Trigger a client-side CSV download. */
function downloadCsv(content: string, fileName: string) {
  const blob = new Blob([content], { type: 'text/csv;charset=utf-8;' });
  const link = document.createElement('a');
  const url = URL.createObjectURL(blob);
  link.setAttribute('href', url);
  link.setAttribute('download', fileName);
  link.style.visibility = 'hidden';
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

export function ProfessionalReportsDashboard() {
  const { user } = useAuth();
  const isSupervisor = user?.role === 'supervisor';

  // Filter state
  const [dateFrom, setDateFrom] = useState(() => {
    const d = new Date();
    d.setDate(d.getDate() - 30);
    return d.toISOString().slice(0, 10);
  });
  const [dateTo, setDateTo] = useState(() => new Date().toISOString().slice(0, 10));
  const [officerId, setOfficerId] = useState<number | undefined>(undefined);
  const [checkpointId, setCheckpointId] = useState<number | undefined>(undefined);
  const [direction, setDirection] = useState<Direction>('all');
  const [decision, setDecision] = useState<Decision>('all');
  const [alertStatus, setAlertStatus] = useState<AlertStatus>('all');

  // Data state
  const [statistics, setStatistics] = useState<any>(null);
  const [chartData, setChartData] = useState<any>(null);
  const [records, setRecords] = useState<any[]>([]);
  const [pagination, setPagination] = useState<any>(null);
  const [currentPage, setCurrentPage] = useState(1);

  // Loading/error state
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  // Dropdown options
  const [officers, setOfficers] = useState<any[]>([]);
  const [checkpoints, setCheckpoints] = useState<any[]>([]);
  const [loadingOptions, setLoadingOptions] = useState(true);

  // Detail drawer
  const [selectedRecord, setSelectedRecord] = useState<any>(null);
  const [detailLoading, setDetailLoading] = useState(false);
  const [detailData, setDetailData] = useState<any>(null);

  // Generated Reports list
  const [showReportsList, setShowReportsList] = useState(false);
  const [previousReports, setPreviousReports] = useState<any[]>([]);
  const [loadingPreviousReports, setLoadingPreviousReports] = useState(false);

  // Generate Report (supervisor action)
  const defaultReportTitle = () => {
    if (checkpointId !== undefined) {
      const cp = checkpoints.find((c) => c.id === checkpointId)?.name ?? 'Checkpoint';
      return direction === 'ENTRY' ? `${cp} Entry Report` : direction === 'EXIT' ? `${cp} Exit Report` : `${cp} Verification Report`;
    }
    if (officerId !== undefined) {
      const off = officers.find((o) => o.id === officerId)?.name ?? 'Officer';
      return `Officer ${off} Verification Report`;
    }
    if (direction === 'ENTRY') return 'Entry Border Crossing Report';
    if (direction === 'EXIT') return 'Exit Border Crossing Report';
    if (alertStatus === 'WARNING') return 'Watchlist Warning Verification Report';
    if (alertStatus === 'CRITICAL') return 'Watchlist Critical Verification Report';
    return 'Border Crossing Verification Report';
  };
  const [reportTitle, setReportTitle] = useState('Border Crossing Verification Report');
  const [titleDirty, setTitleDirty] = useState(false);
  const [generating, setGenerating] = useState(false);

  // Saved report viewer
  const [viewerReport, setViewerReport] = useState<GeneratedReportSnapshot | null>(null);
  const [viewerLoading, setViewerLoading] = useState(false);

  // Keep the title input in sync with the filters until the user edits it manually
  useEffect(() => {
    if (!titleDirty) setReportTitle(defaultReportTitle());
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [checkpointId, officerId, direction, alertStatus, checkpoints, officers]);

  /** Human-readable labels for the currently selected filters. */
  const currentFilterLabels = () => ({
    officer: officerId !== undefined ? officers.find((o) => o.id === officerId)?.name || `Officer #${officerId}` : 'All Officers',
    checkpoint: checkpointId !== undefined ? checkpoints.find((c) => c.id === checkpointId)?.name || `Checkpoint #${checkpointId}` : 'All Checkpoints',
    direction: direction === 'all' ? 'All Directions' : direction,
    decision: decision === 'all' ? 'All Decisions' : decision,
    watchlistStatus: alertStatus === 'all' ? 'All Statuses' : alertStatus,
  });

  /** Assemble the current filter set as a backend payload. */
  const currentFiltersPayload = () => {
    const filters: any = { startDate: dateFrom, endDate: dateTo };
    if (officerId !== undefined) filters.officerId = officerId;
    if (checkpointId !== undefined) filters.checkpointId = checkpointId;
    if (direction !== 'all') filters.direction = direction;
    if (decision !== 'all') filters.decision = decision;
    if (alertStatus !== 'all') filters.alertStatus = alertStatus;
    return filters;
  };

  // Load dropdown options
  useEffect(() => {
    Promise.all([
      reportService.getOfficers(),
      checkpointService.getActive(),
    ])
      .then(([offs, cps]) => {
        setOfficers(offs);
        setCheckpoints(cps);
        setLoadingOptions(false);
      })
      .catch(() => setLoadingOptions(false));
    
    // Load initial report data
    loadReportData();
  }, []);

  // Load report data
  const loadReportData = async () => {
    setLoading(true);
    setError('');

    const filters: any = {
      startDate: dateFrom,
      endDate: dateTo,
    };

    if (officerId !== undefined) filters.officerId = officerId;
    if (checkpointId !== undefined) filters.checkpointId = checkpointId;
    if (direction !== 'all') filters.direction = direction;
    if (decision !== 'all') filters.decision = decision;
    if (alertStatus !== 'all') filters.alertStatus = alertStatus;

    try {
      const [stats, charts, recsData] = await Promise.all([
        reportService.getStatistics(filters),
        reportService.getChartData(filters),
        reportService.getDetailedRecords({ ...filters, page: currentPage, limit: 20 }),
      ]);

      setStatistics(stats);
      setChartData(charts);
      setRecords(recsData.records);
      setPagination(recsData.pagination);
    } catch (err: any) {
      console.error('Report data load error:', err);
      console.error('Error response:', err.response);
      const errorMessage = err.response?.data?.message || err.message || 'Failed to load report data.';
      setError(errorMessage);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    if (!loadingOptions) {
      loadReportData();
    }
  }, [loadingOptions, dateFrom, dateTo, officerId, checkpointId, direction, decision, alertStatus, currentPage]);

  const openDetail = async (recordId: number) => {
    setSelectedRecord(recordId);
    setDetailLoading(true);
    try {
      const detail = await reportService.getVerificationDetail(recordId);
      setDetailData(detail);
    } catch (err) {
      console.error('Failed to load detail:', err);
    } finally {
      setDetailLoading(false);
    }
  };

  const closeDetail = () => {
    setSelectedRecord(null);
    setDetailData(null);
  };

  /** Supervisor action: generate and persist a full report snapshot from the current filters. */
  const handleGenerate = async () => {
    if (!reportTitle.trim()) {
      setError('Please provide a report title before generating.');
      return;
    }
    setGenerating(true);
    setError('');
    try {
      const filters = currentFiltersPayload();
      const report = await reportService.generateReport({
        reportTitle: reportTitle.trim(),
        startDate: filters.startDate,
        endDate: filters.endDate,
        officerId: filters.officerId,
        checkpointId: filters.checkpointId,
        direction: filters.direction,
        decision: filters.decision,
        alertStatus: filters.alertStatus,
      });
      setViewerReport(report);
    } catch (err: any) {
      const errorMessage = err.response?.data?.message || err.message || 'Failed to generate report.';
      setError(errorMessage);
    } finally {
      setGenerating(false);
    }
  };

  /** Open a saved generated report from the list (snapshot data, not live regeneration). */
  const openSavedReport = async (id: number) => {
    setViewerLoading(true);
    try {
      const full = await reportService.getReportById(id);
      setViewerReport(full);
    } catch (err) {
      console.error('Failed to load saved report:', err);
      setError('Failed to load the saved report.');
    } finally {
      setViewerLoading(false);
    }
  };

  // Export the currently filtered live dataset to CSV
  const handleExport = async () => {
    if (!statistics) {
      alert('No report data available. Please wait for the report to load.');
      return;
    }

    setLoading(true);
    try {
      // Fetch ALL filtered records (not just the current page) so the export
      // matches the summary statistics exactly.
      const allRecordsData = await reportService.getDetailedRecords({
        ...currentFiltersPayload(),
        page: 1,
        limit: 100000,
      });
      const rows = (allRecordsData.records || []).map(toReportRow);

      if (rows.length === 0) {
        alert('No records to export for the selected filters.');
        return;
      }

      const csv = buildReportCsv({
        reportTitle: reportTitle.trim() || 'Border Crossing Verification Report',
        generatedBy: user?.name || 'System',
        generatedAt: new Date().toLocaleString(),
        periodFrom: dateFrom,
        periodTo: dateTo,
        filterLabels: currentFilterLabels(),
        statistics,
        chartData,
        records: rows,
      });

      // Audit the export (fire-and-forget) — CSV assembly is client-side.
      api.post('/reports/exported', {
        reportId: null,
        reportTitle: reportTitle.trim() || 'Border Crossing Verification Report',
        recordCount: rows.length,
      }).catch(() => undefined);

      downloadCsv(csv, `Border_Crossing_Report_${dateFrom}_to_${dateTo}.csv`);
    } catch (err) {
      console.error('Export failed:', err);
      alert('Failed to export report. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  // Load generated reports
  const loadPreviousReports = async () => {
    setLoadingPreviousReports(true);
    try {
      const reports = await reportService.getReports();
      setPreviousReports(reports);
      setShowReportsList(true);
    } catch (err) {
      console.error('Failed to load previous reports:', err);
    } finally {
      setLoadingPreviousReports(false);
    }
  };

  return (
    <div className="space-y-6">
      <div>
        <h2 className="text-base font-semibold text-navy-800">Professional Reports Dashboard</h2>
        <p className="text-sm text-navy-400 mt-0.5">
          Comprehensive border crossing analytics with detailed filtering and drill-down capabilities
        </p>
      </div>

      {/* Filters Panel */}
      <div className="card p-6">
        <div className="flex items-center gap-2 mb-4">
          <Filter size={18} className="text-navy-700" />
          <h3 className="text-sm font-semibold text-navy-800">Report Filters</h3>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
          {/* Date From */}
          <div>
            <label className="label">Date From</label>
            <input
              type="date"
              value={dateFrom}
              onChange={(e) => setDateFrom(e.target.value)}
              className="input"
            />
          </div>

          {/* Date To */}
          <div>
            <label className="label">Date To</label>
            <input
              type="date"
              value={dateTo}
              onChange={(e) => setDateTo(e.target.value)}
              className="input"
            />
          </div>

          {/* Officer */}
          <div>
            <label className="label">Officer</label>
            <select
              value={officerId ?? ''}
              onChange={(e) => setOfficerId(e.target.value ? Number(e.target.value) : undefined)}
              className="input"
            >
              <option value="">All Officers</option>
              {officers.map((o) => (
                <option key={o.id} value={o.id}>
                  {o.name}
                </option>
              ))}
            </select>
          </div>

          {/* Checkpoint */}
          <div>
            <label className="label">Checkpoint</label>
            <select
              value={checkpointId ?? ''}
              onChange={(e) => setCheckpointId(e.target.value ? Number(e.target.value) : undefined)}
              className="input"
            >
              <option value="">All Checkpoints</option>
              {checkpoints.map((cp) => (
                <option key={cp.id} value={cp.id}>
                  {cp.name}
                </option>
              ))}
            </select>
          </div>

          {/* Direction */}
          <div>
            <label className="label">Direction</label>
            <select
              value={direction}
              onChange={(e) => setDirection(e.target.value as Direction)}
              className="input"
            >
              <option value="all">All Directions</option>
              <option value="ENTRY">Entry</option>
              <option value="EXIT">Exit</option>
            </select>
          </div>

          {/* Decision */}
          <div>
            <label className="label">Decision</label>
            <select
              value={decision}
              onChange={(e) => setDecision(e.target.value as Decision)}
              className="input"
            >
              <option value="all">All Decisions</option>
              <option value="VERIFIED">Verified</option>
              <option value="PENDING_SUPERVISOR_REVIEW">Pending Review</option>
              <option value="REJECTED">Rejected</option>
            </select>
          </div>

          {/* Watchlist Status */}
          <div>
            <label className="label">Watchlist Status</label>
            <select
              value={alertStatus}
              onChange={(e) => setAlertStatus(e.target.value as AlertStatus)}
              className="input"
            >
              <option value="all">All Statuses</option>
              <option value="NONE">None</option>
              <option value="WARNING">Warning</option>
              <option value="CRITICAL">Critical</option>
            </select>
          </div>

          {/* Reset Button */}
          <div className="flex items-end">
            <button
              onClick={() => {
                setOfficerId(undefined);
                setCheckpointId(undefined);
                setDirection('all');
                setDecision('all');
                setAlertStatus('all');
                setCurrentPage(1);
              }}
              className="btn-secondary w-full"
            >
              Reset Filters
            </button>
          </div>
        </div>
      </div>

      {error && (
        <div className="card bg-accent-red-soft border-red-200 p-4 flex items-center gap-2 text-sm text-accent-red">
          <AlertCircle size={16} /> {error}
        </div>
      )}

      {loading && !statistics ? (
        <div className="card p-12 flex items-center justify-center">
          <Loader2 size={24} className="animate-spin text-navy-400 mr-3" />
          <span className="text-navy-600">Loading report data...</span>
        </div>
      ) : statistics ? (
        <>
          {/* Report Actions */}
          <div className="flex flex-wrap items-center gap-3">
            {isSupervisor && (
              <>
                <div className="flex items-center gap-2 flex-1 min-w-[260px] max-w-md">
                  <input
                    type="text"
                    value={reportTitle}
                    onChange={(e) => { setReportTitle(e.target.value); setTitleDirty(true); }}
                    placeholder="Enter report title..."
                    className="input-field text-sm"
                    aria-label="Report title"
                  />
                </div>
                <button
                  onClick={handleGenerate}
                  disabled={generating}
                  className="btn-primary flex items-center gap-2"
                  title="Generate a saved report snapshot from the current filters"
                >
                  {generating ? (
                    <Loader2 size={16} className="animate-spin" />
                  ) : (
                    <FilePlus2 size={16} />
                  )}
                  Generate Report
                </button>
              </>
            )}
            <div className="flex-1" />
            <button
              onClick={handleExport}
              disabled={!records || records.length === 0}
              className="btn-secondary flex items-center gap-2"
            >
              <Download size={16} /> Export CSV
            </button>
            <button
              onClick={loadPreviousReports}
              disabled={loadingPreviousReports}
              className="btn-secondary flex items-center gap-2"
            >
              {loadingPreviousReports ? (
                <Loader2 size={16} className="animate-spin" />
              ) : (
                <FileBarChart size={16} />
              )}
              Generated Reports
            </button>
          </div>

          {/* Summary Statistics */}
          <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-5 gap-4">
            <StatCard label="Total Crossings" value={statistics.totalCrossings} icon={Building} tone="navy" />
            <StatCard label="Verified" value={statistics.verified} icon={CheckCircle2} tone="green" />
            <StatCard label="Rejected" value={statistics.rejected} icon={XCircle} tone="red" />
            <StatCard label="Pending Review" value={statistics.pendingReview} icon={Clock} tone="amber" />
            <StatCard label="Manual Reviews" value={statistics.manualReviews} icon={Shield} tone="navy" />
          </div>

          <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
            <StatCard label="Entries" value={statistics.entries} icon={ArrowRight} tone="blue" />
            <StatCard label="Exits" value={statistics.exits} icon={ArrowLeft} tone="purple" />
            <StatCard label="Watchlist Warnings" value={statistics.watchlistWarnings} icon={AlertTriangle} tone="amber" />
            <StatCard label="Watchlist Critical" value={statistics.watchlistCritical} icon={ShieldAlert} tone="red" />
          </div>

          {/* Charts */}
          {chartData && (
            <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
              {/* Verification Results Chart */}
              <div className="card p-6">
                <h3 className="text-sm font-semibold text-navy-800 mb-4">Verification Results</h3>
                {chartData.decisions.verified + chartData.decisions.pending + chartData.decisions.rejected > 0 ? (
                  <div className="grid grid-cols-1 md:grid-cols-[140px_1fr] gap-4 items-center">
                    <DonutChart
                      data={[
                        { label: 'Verified', value: chartData.decisions.verified, color: '#16a34a' },
                        { label: 'Pending Supervisor Review', value: chartData.decisions.pending, color: '#d97706' },
                        { label: 'Rejected', value: chartData.decisions.rejected, color: '#dc2626' },
                      ]}
                      size={140}
                    />
                    <ChartLabels
                      data={[
                        { label: 'Verified', value: chartData.decisions.verified, color: '#16a34a' },
                        { label: 'Pending Supervisor Review', value: chartData.decisions.pending, color: '#d97706' },
                        { label: 'Rejected', value: chartData.decisions.rejected, color: '#dc2626' },
                      ]}
                    />
                  </div>
                ) : (
                  <div className="py-8 text-center text-navy-400 text-sm">No data available</div>
                )}
              </div>

              {/* Entry vs Exit Chart */}
              <div className="card p-6">
                <h3 className="text-sm font-semibold text-navy-800 mb-4">Entry vs Exit</h3>
                {chartData.directionBreakdown.entry + chartData.directionBreakdown.exit > 0 ? (
                  <div className="grid grid-cols-1 md:grid-cols-[140px_1fr] gap-4 items-center">
                    <DonutChart
                      data={[
                        { label: 'Entry', value: chartData.directionBreakdown.entry, color: '#0ea5e9' },
                        { label: 'Exit', value: chartData.directionBreakdown.exit, color: '#8b5cf6' },
                      ]}
                      size={140}
                    />
                    <ChartLabels
                      data={[
                        { label: 'Entry', value: chartData.directionBreakdown.entry, color: '#0ea5e9' },
                        { label: 'Exit', value: chartData.directionBreakdown.exit, color: '#8b5cf6' },
                      ]}
                    />
                  </div>
                ) : (
                  <div className="py-8 text-center text-navy-400 text-sm">No data available</div>
                )}
              </div>

              {/* Watchlist Status Chart (optional breakdown; hidden if unavailable) */}
              {chartData.watchlistBreakdown && (
                <div className="card p-6">
                  <h3 className="text-sm font-semibold text-navy-800 mb-4">Watchlist Status</h3>
                  {chartData.watchlistBreakdown.none + chartData.watchlistBreakdown.warning + chartData.watchlistBreakdown.critical > 0 ? (
                    <div className="grid grid-cols-1 md:grid-cols-[140px_1fr] gap-4 items-center">
                      <DonutChart
                        data={[
                          { label: 'None', value: chartData.watchlistBreakdown.none, color: '#64748b' },
                          { label: 'Warning', value: chartData.watchlistBreakdown.warning, color: '#f59e0b' },
                          { label: 'Critical', value: chartData.watchlistBreakdown.critical, color: '#dc2626' },
                        ]}
                        size={140}
                      />
                      <ChartLabels
                        data={[
                          { label: 'None', value: chartData.watchlistBreakdown.none, color: '#64748b' },
                          { label: 'Warning', value: chartData.watchlistBreakdown.warning, color: '#f59e0b' },
                          { label: 'Critical', value: chartData.watchlistBreakdown.critical, color: '#dc2626' },
                        ]}
                      />
                    </div>
                  ) : (
                    <div className="py-8 text-center text-navy-400 text-sm">No data available</div>
                  )}
                </div>
              )}
            </div>
          )}

          {/* Detailed Records Table */}
          <div className="card overflow-hidden">
            <div className="px-5 py-4 border-b border-navy-100">
              <h3 className="text-sm font-semibold text-navy-800">Detailed Verification Records</h3>
              <p className="text-xs text-navy-400 mt-0.5">Click any row to view complete verification details</p>
            </div>

            <div className="overflow-x-auto">
              {records.length === 0 ? (
                <div className="py-12 text-center text-navy-400 text-sm">
                  No verification records found for the selected filters and date range.
                </div>
              ) : (
                <table className="w-full text-sm">
                  <thead className="bg-navy-50">
                    <tr>
                      <th className="table-header px-4 py-3">Date/Time</th>
                      <th className="table-header px-4 py-3">Traveler</th>
                      <th className="table-header px-4 py-3">FAN</th>
                      <th className="table-header px-4 py-3">Officer</th>
                      <th className="table-header px-4 py-3">Checkpoint</th>
                      <th className="table-header px-4 py-3">Direction</th>
                      <th className="table-header px-4 py-3">FP Score</th>
                      <th className="table-header px-4 py-3">Iris Score</th>
                      <th className="table-header px-4 py-3">Overall</th>
                      <th className="table-header px-4 py-3">Threshold</th>
                      <th className="table-header px-4 py-3">Watchlist</th>
                      <th className="table-header px-4 py-3">Decision</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-navy-100">
                    {records.map((record) => (
                      <tr
                        key={record.id}
                        onClick={() => openDetail(record.id)}
                        className="hover:bg-navy-50/60 transition-colors cursor-pointer"
                      >
                        <td className="px-4 py-3 whitespace-nowrap text-xs text-navy-600">
                          {new Date(record.timestamp).toLocaleString()}
                        </td>
                        <td className="px-4 py-3">
                          <div className="font-medium text-navy-800">{record.traveler.fullName}</div>
                          <div className="text-xs text-navy-400">{record.traveler.nationality}</div>
                        </td>
                        <td className="px-4 py-3 font-mono text-xs text-navy-600">{record.traveler.fan}</td>
                        <td className="px-4 py-3 text-navy-600 text-xs">{record.officer.name}</td>
                        <td className="px-4 py-3 text-navy-600 text-xs">{record.checkpoint?.name || '—'}</td>
                        <td className="px-4 py-3">
                          <span
                            className={`text-xs font-semibold px-2 py-1 rounded ${
                              record.direction === 'ENTRY'
                                ? 'bg-blue-100 text-blue-700'
                                : 'bg-purple-100 text-purple-700'
                            }`}
                          >
                            {record.direction}
                          </span>
                        </td>
                        <td className="px-4 py-3 text-center">
                          <ScorePill score={record.fingerprintScore} />
                        </td>
                        <td className="px-4 py-3 text-center">
                          <ScorePill score={record.irisScore} />
                        </td>
                        <td className="px-4 py-3 text-center">
                          <ScorePill score={record.finalScore} bold />
                        </td>
                        <td className="px-4 py-3 text-center text-xs text-navy-500 font-medium">
                          {record.threshold}%
                        </td>
                        <td className="px-4 py-3">
                          <span
                            className={`text-xs font-bold ${
                              record.alertStatusAtVerification === 'CRITICAL'
                                ? 'text-accent-red'
                                : record.alertStatusAtVerification === 'WARNING'
                                ? 'text-accent-amber'
                                : 'text-accent-green'
                            }`}
                          >
                            {record.alertStatusAtVerification || 'NONE'}
                          </span>
                        </td>
                        <td className="px-4 py-3">
                          <StatusBadge
                            status={
                              record.finalDecision === 'VERIFIED'
                                ? 'verified'
                                : record.finalDecision === 'REJECTED'
                                ? 'rejected'
                                : 'pending'
                            }
                          />
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              )}
            </div>

            {/* Pagination */}
            {pagination && pagination.totalPages > 1 && (
              <div className="px-5 py-4 border-t border-navy-100 flex items-center justify-between">
                <span className="text-xs text-navy-400">
                  Showing {(pagination.page - 1) * pagination.limit + 1}–
                  {Math.min(pagination.page * pagination.limit, pagination.total)} of {pagination.total}
                </span>
                <div className="flex items-center gap-2">
                  <button
                    onClick={() => setCurrentPage((p) => Math.max(1, p - 1))}
                    disabled={currentPage === 1}
                    className="btn-secondary text-xs px-3 py-1.5 disabled:opacity-40"
                  >
                    Previous
                  </button>
                  <span className="text-sm text-navy-600 font-medium px-3">
                    Page {currentPage} of {pagination.totalPages}
                  </span>
                  <button
                    onClick={() => setCurrentPage((p) => Math.min(pagination.totalPages, p + 1))}
                    disabled={currentPage === pagination.totalPages}
                    className="btn-secondary text-xs px-3 py-1.5 disabled:opacity-40"
                  >
                    Next
                  </button>
                </div>
              </div>
            )}
          </div>
        </>
      ) : null}

      {/* Generated Report Viewer (rendered before DetailDrawer so record details stack on top) */}
      {viewerLoading && (
        <div className="fixed inset-0 bg-black/50 z-50 flex items-center justify-center">
          <div className="bg-white rounded-lg p-8 flex items-center gap-3">
            <Loader2 size={20} className="animate-spin text-navy-500" />
            <span className="text-sm text-navy-600">Loading report...</span>
          </div>
        </div>
      )}
      {!viewerLoading && viewerReport && (
        <ReportViewer
          report={viewerReport}
          userRole={user?.role}
          onClose={() => setViewerReport(null)}
          onOpenVerification={(id) => openDetail(id)}
        />
      )}

      {/* Detail Drawer */}
      {selectedRecord && (
        <DetailDrawer
          isOpen={!!selectedRecord}
          onClose={closeDetail}
          loading={detailLoading}
          data={detailData}
        />
      )}

      {/* Generated Reports List */}
      {showReportsList && (
        <div className="fixed inset-0 bg-black/50 z-50 flex items-center justify-center p-4">
          <div className="bg-white rounded-lg w-full max-w-5xl max-h-[90vh] overflow-hidden flex flex-col">
            <div className="px-6 py-4 border-b border-navy-100 flex items-center justify-between">
              <div>
                <h2 className="text-base font-semibold text-navy-800">Generated Reports</h2>
                <p className="text-xs text-navy-400 mt-0.5">Click any report to view its saved snapshot</p>
              </div>
              <button onClick={() => setShowReportsList(false)} className="btn-secondary">
                <X size={16} /> Close
              </button>
            </div>
            <div className="flex-1 overflow-y-auto p-6">
              {previousReports.length === 0 ? (
                <div className="text-center py-12 text-navy-400 text-sm">
                  No generated reports yet. Use “Generate Report” to create one from the current filters.
                </div>
              ) : (
                <table className="w-full text-sm">
                  <thead className="bg-navy-50">
                    <tr>
                      <th className="table-header px-4 py-3 text-left">Title</th>
                      <th className="table-header px-4 py-3 text-left">Generated By</th>
                      <th className="table-header px-4 py-3 text-left">Generated</th>
                      <th className="table-header px-4 py-3 text-left">Period</th>
                      <th className="table-header px-4 py-3 text-center">Records</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-navy-100">
                    {previousReports.map((report) => (
                      <tr
                        key={report.id}
                        onClick={() => {
                          setShowReportsList(false);
                          openSavedReport(Number(report.id));
                        }}
                        className="hover:bg-navy-50/60 transition-colors cursor-pointer"
                      >
                        <td className="px-4 py-3">
                          <div className="flex items-center gap-2">
                            <FileBarChart size={15} className="text-navy-500 shrink-0" />
                            <span className="font-medium text-navy-800">{report.name}</span>
                          </div>
                        </td>
                        <td className="px-4 py-3 text-navy-600 text-xs">{report.generatedBy}</td>
                        <td className="px-4 py-3 whitespace-nowrap text-xs text-navy-600">{report.date}</td>
                        <td className="px-4 py-3 whitespace-nowrap text-xs text-navy-600">
                          {report.startDate} – {report.endDate}
                        </td>
                        <td className="px-4 py-3 text-center">
                          <span className="badge-neutral text-xs">{report.recordCount ?? '—'}</span>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              )}
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

function StatCard({
  label,
  value,
  icon: Icon,
  tone,
}: {
  label: string;
  value: number;
  icon: any;
  tone: 'navy' | 'green' | 'red' | 'amber' | 'blue' | 'purple';
}) {
  const toneMap = {
    navy: { bg: 'bg-navy-100', text: 'text-navy-700' },
    green: { bg: 'bg-accent-green-soft', text: 'text-accent-green' },
    red: { bg: 'bg-accent-red-soft', text: 'text-accent-red' },
    amber: { bg: 'bg-accent-amber-soft', text: 'text-accent-amber' },
    blue: { bg: 'bg-blue-100', text: 'text-blue-700' },
    purple: { bg: 'bg-purple-100', text: 'text-purple-700' },
  };
  const t = toneMap[tone];
  return (
    <div className="card p-4">
      <div className="flex items-start justify-between">
        <div className="flex-1">
          <div className="text-xs font-medium text-navy-400 uppercase tracking-wide">{label}</div>
          <div className="mt-2 text-2xl font-bold text-navy-800">{value.toLocaleString()}</div>
        </div>
        <div className={`h-10 w-10 rounded-lg ${t.bg} ${t.text} flex items-center justify-center shrink-0`}>
          <Icon size={20} />
        </div>
      </div>
    </div>
  );
}

function ScorePill({ score, bold }: { score: number; bold?: boolean }) {
  const color = score >= 95 ? '#16a34a' : score >= 85 ? '#d97706' : '#dc2626';
  return (
    <span
      className={`text-xs ${bold ? 'font-bold' : 'font-semibold'} px-2 py-1 rounded`}
      style={{ color, backgroundColor: `${color}20` }}
    >
      {score}%
    </span>
  );
}

function DetailDrawer({
  isOpen,
  onClose,
  loading,
  data,
}: {
  isOpen: boolean;
  onClose: () => void;
  loading: boolean;
  data: any;
}) {
  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 bg-black/50 z-50 flex justify-end">
      <div className="bg-white w-full max-w-3xl h-full overflow-y-auto">
        {/* Header */}
        <div className="sticky top-0 bg-white border-b border-navy-100 px-6 py-4 flex items-center justify-between z-10">
          <div>
            <h2 className="text-base font-semibold text-navy-800">Verification Detail</h2>
            <p className="text-xs text-navy-400 mt-0.5">Complete border crossing information</p>
          </div>
          <button onClick={onClose} className="btn-secondary">
            <X size={16} /> Close
          </button>
        </div>

        {/* Content */}
        <div className="p-6">
          {loading ? (
            <div className="flex items-center justify-center py-12">
              <Loader2 size={24} className="animate-spin text-navy-400 mr-3" />
              <span className="text-navy-600">Loading details...</span>
            </div>
          ) : data ? (
            <div className="space-y-6">
              {/* Traveler Section */}
              <DetailSection title="Traveler Information">
                <div className="grid grid-cols-2 gap-4">
                  <DetailField label="Full Name" value={data.traveler.fullName} />
                  <DetailField label="FAN" value={data.traveler.fan} mono />
                  <DetailField label="Nationality" value={data.traveler.nationality} />
                  <DetailField
                    label="Date of Birth"
                    value={new Date(data.traveler.dateOfBirth).toLocaleDateString()}
                  />
                  <DetailField label="Gender" value={data.traveler.gender} />
                  <DetailField label="Enrollment Status" value={data.traveler.enrollmentStatus} />
                </div>
              </DetailSection>

              {/* Border Crossing Section */}
              <DetailSection title="Border Crossing">
                <div className="grid grid-cols-2 gap-4">
                  <DetailField
                    label="Date/Time"
                    value={new Date(data.timestamp).toLocaleString()}
                  />
                  <DetailField label="Checkpoint" value={data.checkpoint?.name || 'N/A'} />
                  <DetailField label="Location" value={data.checkpoint?.location || 'N/A'} />
                  <DetailField label="Direction" value={data.direction || 'N/A'} />
                  <DetailField label="Officer" value={data.officer.name} />
                  <DetailField
                    label="Final Decision"
                    value={
                      data.finalDecision === 'VERIFIED'
                        ? 'VERIFIED'
                        : data.finalDecision === 'REJECTED'
                        ? 'REJECTED'
                        : 'PENDING REVIEW'
                    }
                  />
                </div>
              </DetailSection>

              {/* Watchlist Information */}
              <DetailSection title="Watchlist Information">
                <div className="grid grid-cols-2 gap-4">
                  <DetailField
                    label="Alert Status at Verification"
                    value={data.alertStatusAtVerification || 'NONE'}
                    badge
                    badgeColor={
                      data.alertStatusAtVerification === 'CRITICAL'
                        ? 'red'
                        : data.alertStatusAtVerification === 'WARNING'
                        ? 'amber'
                        : 'green'
                    }
                  />
                  <DetailField
                    label="Alert Reason"
                    value={data.alertReasonAtVerification || 'None'}
                  />
                </div>
                {data.alertStatusAtVerification && data.alertStatusAtVerification !== 'NONE' && (
                  <div className="mt-3 p-3 bg-accent-amber-soft rounded-lg border border-amber-200">
                    <p className="text-xs text-amber-800">
                      <strong>Note:</strong> This is the watchlist status at the time of verification. The
                      traveler's current status may differ.
                    </p>
                  </div>
                )}
              </DetailSection>

              {/* Biometric Verification */}
              <DetailSection title="Biometric Verification">
                <div className="space-y-4">
                  <div className="grid grid-cols-3 gap-4">
                    <div className="card p-4">
                      <div className="flex items-center gap-2 text-navy-500 mb-2">
                        <Fingerprint size={16} />
                        <span className="text-xs font-semibold uppercase">Fingerprint</span>
                      </div>
                      <div className="text-2xl font-bold text-navy-800">{data.fingerprintScore}%</div>
                      <div className="text-xs text-navy-400 mt-1">Match Score</div>
                    </div>

                    <div className="card p-4">
                      <div className="flex items-center gap-2 text-navy-500 mb-2">
                        <ScanEye size={16} />
                        <span className="text-xs font-semibold uppercase">Iris</span>
                      </div>
                      <div className="text-2xl font-bold text-navy-800">{data.irisScore}%</div>
                      <div className="text-xs text-navy-400 mt-1">Match Score</div>
                    </div>

                    <div className="card p-4 bg-navy-50">
                      <div className="flex items-center gap-2 text-navy-700 mb-2">
                        <Shield size={16} />
                        <span className="text-xs font-semibold uppercase">Overall</span>
                      </div>
                      <div className="text-2xl font-bold text-navy-800">{data.finalScore}%</div>
                      <div className="text-xs text-navy-600 mt-1">Final Confidence</div>
                    </div>
                  </div>

                  <div className="grid grid-cols-2 gap-4">
                    <DetailField label="Threshold Used" value={`${data.threshold}%`} />
                    <DetailField
                      label="System Decision"
                      value={data.systemDecision || data.finalDecision}
                    />
                  </div>
                </div>
              </DetailSection>

              {/* Decision Section */}
              {data.decisionReason && (
                <DetailSection title="Decision">
                  <DetailField label="Decision Reason" value={data.decisionReason} />
                </DetailSection>
              )}

              {/* Manual Review Section */}
              {data.manualReviewRequest && (
                <DetailSection title="Manual Review">
                  <div className="grid grid-cols-2 gap-4">
                    <DetailField label="Reason" value={data.manualReviewRequest.reason.replace(/_/g, ' ')} />
                    <DetailField label="Status" value={data.manualReviewRequest.status} />
                    {data.manualReviewRequest.decision && (
                      <DetailField label="Supervisor Decision" value={data.manualReviewRequest.decision} />
                    )}
                    {data.manualReviewRequest.supervisor && (
                      <DetailField label="Supervisor" value={data.manualReviewRequest.supervisor.name} />
                    )}
                  </div>
                  {data.manualReviewRequest.supervisorNotes && (
                    <div className="mt-3">
                      <DetailField label="Supervisor Notes" value={data.manualReviewRequest.supervisorNotes} />
                    </div>
                  )}
                </DetailSection>
              )}
            </div>
          ) : (
            <div className="text-center py-12 text-navy-400">No data available</div>
          )}
        </div>
      </div>
    </div>
  );
}

function DetailSection({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="card p-5">
      <h3 className="text-sm font-semibold text-navy-800 mb-4 pb-2 border-b border-navy-100">{title}</h3>
      {children}
    </div>
  );
}

function DetailField({
  label,
  value,
  mono,
  badge,
  badgeColor,
}: {
  label: string;
  value: string;
  mono?: boolean;
  badge?: boolean;
  badgeColor?: 'green' | 'amber' | 'red';
}) {
  return (
    <div>
      <div className="text-xs text-navy-400 uppercase tracking-wide font-medium mb-1">{label}</div>
      {badge ? (
        <span
          className={`inline-block text-xs font-bold px-2 py-1 rounded ${
            badgeColor === 'red'
              ? 'bg-accent-red-soft text-accent-red'
              : badgeColor === 'amber'
              ? 'bg-accent-amber-soft text-accent-amber'
              : 'bg-accent-green-soft text-accent-green'
          }`}
        >
          {value}
        </span>
      ) : (
        <div className={`text-sm font-medium text-navy-800 ${mono ? 'font-mono' : ''}`}>{value}</div>
      )}
    </div>
  );
}

/**
 * Full-screen viewer for a saved generated report. Renders exclusively from the
 * stored snapshot (metadata, statistics, charts, records) so the report stays
 * historically accurate even if live data changes later.
 */
function ReportViewer({
  report,
  userRole,
  onClose,
  onOpenVerification,
}: {
  report: GeneratedReportSnapshot;
  userRole?: string;
  onClose: () => void;
  onOpenVerification: (verificationId: number) => void;
}) {
  const stats = report.summaryData;
  const charts = report.chartData;
  const snapshotRows = (report.recordsData || []).map(snapshotToRow);
  const labels = report.filters?.labels;

  const handleExportSnapshot = () => {
    if (!stats) return;
    // Audit the export (fire-and-forget) — the CSV itself is built in the browser.
    api.post('/reports/exported', {
      reportId: report.id,
      reportTitle: report.reportTitle,
      recordCount: snapshotRows.length,
    }).catch(() => undefined);
    const csv = buildReportCsv({
      reportTitle: report.reportTitle,
      generatedBy: report.generatedByUser?.name || 'System',
      generatedAt: new Date(report.createdAt).toLocaleString(),
      periodFrom: new Date(report.startDate).toISOString().slice(0, 10),
      periodTo: new Date(report.endDate).toISOString().slice(0, 10),
      filterLabels: labels || {
        officer: report.filters?.officerId != null ? `Officer #${report.filters.officerId}` : 'All Officers',
        checkpoint: report.filters?.checkpointId != null ? `Checkpoint #${report.filters.checkpointId}` : 'All Checkpoints',
        direction: report.filters?.direction ?? 'All Directions',
        decision: report.filters?.decision ?? 'All Decisions',
        watchlistStatus: report.filters?.alertStatus ?? 'All Statuses',
      },
      statistics: stats,
      chartData: charts ?? null,
      records: snapshotRows,
    });
    downloadCsv(
      csv,
      `${report.reportTitle.replace(/[^a-z0-9]+/gi, '_')}_${new Date(report.startDate).toISOString().slice(0, 10)}.csv`
    );
  };

  return (
    <div className="fixed inset-0 bg-black/50 z-50 flex items-start justify-center p-4 overflow-y-auto">
      <div className="bg-white rounded-lg w-full max-w-6xl my-4 overflow-hidden flex flex-col">
        {/* Header */}
        <div className="px-6 py-4 border-b border-navy-100 flex items-center justify-between">
          <div>
            <p className="text-[11px] uppercase tracking-wide text-navy-400 font-semibold">
              Intelligent Automated Border Control System
            </p>
            <h2 className="text-base font-semibold text-navy-800 mt-0.5">{report.reportTitle}</h2>
          </div>
          <div className="flex items-center gap-2">
            {userRole === 'admin' && (
              <span className="badge-neutral text-xs">Read-only view</span>
            )}
            {stats && (
              <button onClick={handleExportSnapshot} className="btn-secondary flex items-center gap-2">
                <Download size={15} /> Export CSV
              </button>
            )}
            <button onClick={onClose} className="btn-secondary">
              <X size={16} /> Close
            </button>
          </div>
        </div>

        <div className="flex-1 overflow-y-auto p-6 space-y-6">
          {/* Metadata */}
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
            <DetailField label="Generated By" value={report.generatedByUser?.name || 'System'} />
            <DetailField label="Generated Date" value={new Date(report.createdAt).toLocaleString()} />
            <DetailField
              label="Report Period"
              value={`${new Date(report.startDate).toLocaleDateString()} – ${new Date(report.endDate).toLocaleDateString()}`}
            />
            <DetailField label="Records Included" value={String(report.recordCount)} />
          </div>

          {/* Applied Filters */}
          <div className="card p-4">
            <h3 className="text-xs font-semibold text-navy-400 uppercase tracking-wide mb-3">Applied Filters</h3>
            <div className="flex flex-wrap gap-2">
              {labels ? (
                <>
                  <FilterChip icon={User} label={labels.officer} />
                  <FilterChip icon={MapPin} label={labels.checkpoint} />
                  <FilterChip icon={(labels.direction === 'ENTRY' ? ArrowRight : labels.direction === 'EXIT' ? ArrowLeft : Filter) as any} label={labels.direction} />
                  <FilterChip icon={Shield} label={labels.decision} />
                  <FilterChip icon={ScanEye} label={labels.watchlistStatus} />
                </>
              ) : (
                <>
                  <FilterChip icon={User} label={report.filters?.officerId != null ? `Officer #${report.filters.officerId}` : 'All Officers'} />
                  <FilterChip icon={MapPin} label={report.filters?.checkpointId != null ? `Checkpoint #${report.filters.checkpointId}` : 'All Checkpoints'} />
                  <FilterChip icon={Filter} label={report.filters?.direction ?? 'All Directions'} />
                  <FilterChip icon={Shield} label={report.filters?.decision ?? 'All Decisions'} />
                  <FilterChip icon={ScanEye} label={report.filters?.alertStatus ?? 'All Statuses'} />
                </>
              )}
            </div>
          </div>

          {!stats ? (
            <div className="card p-8 text-center text-navy-400 text-sm">
              This report was saved without statistical data and only contains its metadata.
            </div>
          ) : (
            <>
              {/* Summary Statistics */}
              <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-5 gap-4">
                <StatCard label="Total Crossings" value={stats.totalCrossings} icon={Building} tone="navy" />
                <StatCard label="Verified" value={stats.verified} icon={CheckCircle2} tone="green" />
                <StatCard label="Rejected" value={stats.rejected} icon={XCircle} tone="red" />
                <StatCard label="Pending Supervisor Review" value={stats.pendingReview} icon={Clock} tone="amber" />
                <StatCard label="Manual Reviews" value={stats.manualReviews} icon={Shield} tone="navy" />
              </div>

              {/* Charts */}
              {charts && (
                <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
                  <div className="card p-6">
                    <h3 className="text-sm font-semibold text-navy-800 mb-4">Verification Results</h3>
                    {charts.decisions.verified + charts.decisions.pending + charts.decisions.rejected > 0 ? (
                      <div className="grid grid-cols-1 md:grid-cols-[140px_1fr] gap-4 items-center">
                        <DonutChart
                          data={[
                            { label: 'Verified', value: charts.decisions.verified, color: '#16a34a' },
                            { label: 'Pending Supervisor Review', value: charts.decisions.pending, color: '#d97706' },
                            { label: 'Rejected', value: charts.decisions.rejected, color: '#dc2626' },
                          ]}
                          size={140}
                        />
                        <ChartLabels
                          data={[
                            { label: 'Verified', value: charts.decisions.verified, color: '#16a34a' },
                            { label: 'Pending Supervisor Review', value: charts.decisions.pending, color: '#d97706' },
                            { label: 'Rejected', value: charts.decisions.rejected, color: '#dc2626' },
                          ]}
                        />
                      </div>
                    ) : (
                      <div className="py-8 text-center text-navy-400 text-sm">No data available</div>
                    )}
                  </div>

                  <div className="card p-6">
                    <h3 className="text-sm font-semibold text-navy-800 mb-4">Entry vs Exit</h3>
                    {charts.directionBreakdown.entry + charts.directionBreakdown.exit > 0 ? (
                      <div className="grid grid-cols-1 md:grid-cols-[140px_1fr] gap-4 items-center">
                        <DonutChart
                          data={[
                            { label: 'Entry', value: charts.directionBreakdown.entry, color: '#0ea5e9' },
                            { label: 'Exit', value: charts.directionBreakdown.exit, color: '#8b5cf6' },
                          ]}
                          size={140}
                        />
                        <ChartLabels
                          data={[
                            { label: 'Entry', value: charts.directionBreakdown.entry, color: '#0ea5e9' },
                            { label: 'Exit', value: charts.directionBreakdown.exit, color: '#8b5cf6' },
                          ]}
                        />
                      </div>
                    ) : (
                      <div className="py-8 text-center text-navy-400 text-sm">No data available</div>
                    )}
                  </div>

                  {charts.watchlistBreakdown && (
                    <div className="card p-6">
                      <h3 className="text-sm font-semibold text-navy-800 mb-4">Watchlist Status</h3>
                      {charts.watchlistBreakdown.none + charts.watchlistBreakdown.warning + charts.watchlistBreakdown.critical > 0 ? (
                        <div className="grid grid-cols-1 md:grid-cols-[140px_1fr] gap-4 items-center">
                          <DonutChart
                            data={[
                              { label: 'None', value: charts.watchlistBreakdown.none, color: '#64748b' },
                              { label: 'Warning', value: charts.watchlistBreakdown.warning, color: '#f59e0b' },
                              { label: 'Critical', value: charts.watchlistBreakdown.critical, color: '#dc2626' },
                            ]}
                            size={140}
                          />
                          <ChartLabels
                            data={[
                              { label: 'None', value: charts.watchlistBreakdown.none, color: '#64748b' },
                              { label: 'Warning', value: charts.watchlistBreakdown.warning, color: '#f59e0b' },
                              { label: 'Critical', value: charts.watchlistBreakdown.critical, color: '#dc2626' },
                            ]}
                          />
                        </div>
                      ) : (
                        <div className="py-8 text-center text-navy-400 text-sm">No data available</div>
                      )}
                    </div>
                  )}
                </div>
              )}

              {/* Snapshot Records Table */}
              <div className="card overflow-hidden">
                <div className="px-5 py-4 border-b border-navy-100">
                  <h3 className="text-sm font-semibold text-navy-800">Detailed Verification Records</h3>
                  <p className="text-xs text-navy-400 mt-0.5">
                    Click any row to view the complete verification details
                  </p>
                </div>
                <div className="overflow-x-auto">
                  {snapshotRows.length === 0 ? (
                    <div className="py-12 text-center text-navy-400 text-sm">
                      No verification records found for the selected filters and date range.
                    </div>
                  ) : (
                    <table className="w-full text-sm">
                      <thead className="bg-navy-50">
                        <tr>
                          <th className="table-header px-4 py-3">Date/Time</th>
                          <th className="table-header px-4 py-3">Traveler</th>
                          <th className="table-header px-4 py-3">FAN</th>
                          <th className="table-header px-4 py-3">Officer</th>
                          <th className="table-header px-4 py-3">Checkpoint</th>
                          <th className="table-header px-4 py-3">Direction</th>
                          <th className="table-header px-4 py-3">FP Score</th>
                          <th className="table-header px-4 py-3">Iris Score</th>
                          <th className="table-header px-4 py-3">Overall</th>
                          <th className="table-header px-4 py-3">Threshold</th>
                          <th className="table-header px-4 py-3">Watchlist</th>
                          <th className="table-header px-4 py-3">Decision</th>
                        </tr>
                      </thead>
                      <tbody className="divide-y divide-navy-100">
                        {snapshotRows.map((row) => (
                          <tr
                            key={row.verificationId}
                            onClick={() => onOpenVerification(row.verificationId)}
                            className="hover:bg-navy-50/60 transition-colors cursor-pointer"
                          >
                            <td className="px-4 py-3 whitespace-nowrap text-xs text-navy-600">
                              {new Date(row.timestamp).toLocaleString()}
                            </td>
                            <td className="px-4 py-3">
                              <div className="font-medium text-navy-800">{row.travelerName ?? '-'}</div>
                            </td>
                            <td className="px-4 py-3 font-mono text-xs text-navy-600">{row.travelerFan ?? '-'}</td>
                            <td className="px-4 py-3 text-navy-600 text-xs">{row.officerName ?? '-'}</td>
                            <td className="px-4 py-3 text-navy-600 text-xs">{row.checkpointName ?? '-'}</td>
                            <td className="px-4 py-3">
                              <span
                                className={`text-xs font-semibold px-2 py-1 rounded ${
                                  row.direction === 'ENTRY'
                                    ? 'bg-blue-100 text-blue-700'
                                    : 'bg-purple-100 text-purple-700'
                                }`}
                              >
                                {row.direction}
                              </span>
                            </td>
                            <td className="px-4 py-3 text-center">
                              <ScorePill score={row.fingerprintScore} />
                            </td>
                            <td className="px-4 py-3 text-center">
                              <ScorePill score={row.irisScore} />
                            </td>
                            <td className="px-4 py-3 text-center">
                              <ScorePill score={row.finalScore} bold />
                            </td>
                            <td className="px-4 py-3 text-center text-xs text-navy-500 font-medium">
                              {row.threshold}%
                            </td>
                            <td className="px-4 py-3">
                              <span
                                className={`text-xs font-bold ${
                                  row.alertStatusAtVerification === 'CRITICAL'
                                    ? 'text-accent-red'
                                    : row.alertStatusAtVerification === 'WARNING'
                                    ? 'text-accent-amber'
                                    : 'text-accent-green'
                                }`}
                              >
                                {row.alertStatusAtVerification || 'NONE'}
                              </span>
                            </td>
                            <td className="px-4 py-3">
                              <StatusBadge
                                status={
                                  row.finalDecision === 'VERIFIED'
                                    ? 'verified'
                                    : row.finalDecision === 'REJECTED'
                                    ? 'rejected'
                                    : 'pending'
                                }
                              />
                            </td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  )}
                </div>
              </div>
            </>
          )}
        </div>
      </div>
    </div>
  );
}

function FilterChip({ icon: Icon, label }: { icon: any; label: string }) {
  return (
    <span className="inline-flex items-center gap-1.5 text-xs bg-navy-50 text-navy-700 px-3 py-1.5 rounded-full">
      <Icon size={12} /> {label}
    </span>
  );
}
