import { useState, useEffect } from 'react';
import { useAuth } from '../context/AuthContext';
import {
  reportService,
  type ReportRecord,
  type ReportParams,
  type VerificationSummaryResponse,
  type OverrideSummaryResponse,
  type OfficerActivitySummaryResponse,
} from '../services/reportService';
import { BarChart, AxisLabels, DonutChart, ChartLabels } from '../components/Charts';
import { FileBarChart, Download, Calendar, Filter, FileText, CheckCircle2, Loader2, AlertCircle } from 'lucide-react';

type ReportType = 'verification' | 'override' | 'officer';
type GeneratedReport = VerificationSummaryResponse | OverrideSummaryResponse | OfficerActivitySummaryResponse;

export function ReportsDashboard() {
  const { user } = useAuth();
  const [reportType, setReportType] = useState<ReportType>('verification');
  const [dateRange, setDateRange] = useState<'7d' | '30d' | '90d' | 'ytd'>('7d');
  const [selectedOfficer, setSelectedOfficer] = useState('');
  const [generated, setGenerated] = useState(false);
  const [generating, setGenerating] = useState(false);
  const [reportData, setReportData] = useState<GeneratedReport | null>(null);
  const [genError, setGenError] = useState('');

  const [prevReports, setPrevReports] = useState<ReportRecord[]>([]);
  const [prevLoading, setPrevLoading] = useState(true);
  const [prevError, setPrevError] = useState('');

  // Previous reports filters
  const [prevDate, setPrevDate] = useState<'all' | '7d' | '30d' | '90d'>('all');
  const [prevBy, setPrevBy] = useState<'all' | string>('all');
  const [prevType, setPrevType] = useState<'all' | ReportType>('all');

  useEffect(() => {
    reportService
      .getReports()
      .then((data) => { setPrevReports(data); setPrevLoading(false); })
      .catch(() => { setPrevError('Failed to load previous reports.'); setPrevLoading(false); });
  }, []);

  const typeLabel: Record<ReportType, string> = {
    verification: 'Verification Summary',
    override: 'Override Summary',
    officer: 'Officer Activity',
  };

  const dateRangeToParams = (range: '7d' | '30d' | '90d' | 'ytd'): ReportParams => {
    const now = new Date();
    const end = now.toISOString().slice(0, 10);
    let start: string;
    if (range === '7d') start = new Date(now.getTime() - 7 * 86400000).toISOString().slice(0, 10);
    else if (range === '30d') start = new Date(now.getTime() - 30 * 86400000).toISOString().slice(0, 10);
    else if (range === '90d') start = new Date(now.getTime() - 90 * 86400000).toISOString().slice(0, 10);
    else start = new Date(now.getFullYear(), 0, 1).toISOString().slice(0, 10);
    return { startDate: start, endDate: end };
  };

  const handleGenerate = async () => {
    setGenerating(true);
    setGenerated(false);
    setGenError('');
    try {
      const params = dateRangeToParams(dateRange);
      if (reportType === 'verification') {
        const data = await reportService.verificationSummary(params);
        setReportData(data);
      } else if (reportType === 'override') {
        const data = await reportService.overrideSummary(params);
        setReportData(data);
      } else {
        const data = await reportService.officerActivity({ ...params, officerId: selectedOfficer });
        setReportData(data);
      }
      setGenerated(true);
    } catch (err: unknown) {
      const msg =
        (err as { response?: { data?: { message?: string } } })?.response?.data?.message ??
        'Failed to generate report.';
      setGenError(msg);
    } finally {
      setGenerating(false);
    }
  };

  const handleDownloadCSV = (dataToExport?: GeneratedReport, typeToExport?: ReportType) => {
    const targetData = dataToExport || reportData;
    const targetType = typeToExport || reportType;
    if (!targetData) return;

    const params = dateRangeToParams(dateRange);
    const nowStr = new Date().toLocaleString();
    const todayStr = new Date().toISOString().slice(0, 10);
    const userName = user?.name || 'System Administrator';

    const lines: string[] = [];
    lines.push(`Report Type,${typeLabel[targetType]}`);
    lines.push(`Date Range,${params.startDate} to ${params.endDate}`);
    lines.push(`Generated By,"${userName}"`);
    lines.push(`Generated Date,"${nowStr}"`);
    lines.push(''); // blank row separator

    if (targetType === 'verification') {
      const summary = (targetData as VerificationSummaryResponse).summary || { total: 0, verified: 0, pendingSupervisorReview: 0, rejected: 0 };
      lines.push('Metric,Value');
      lines.push(`Total Verifications,${summary.total ?? 0}`);
      lines.push(`Verified,${summary.verified ?? 0}`);
      lines.push(`Pending Supervisor Review,${summary.pendingSupervisorReview ?? 0}`);
      lines.push(`Rejected,${summary.rejected ?? 0}`);
    } else if (targetType === 'override') {
      const summary = (targetData as OverrideSummaryResponse).summary || { total: 0, approvedToVerified: 0, approvedToRejected: 0 };
      lines.push('Metric,Value');
      lines.push(`Total Overrides,${summary.total ?? 0}`);
      lines.push(`Approved to Verified,${summary.approvedToVerified ?? 0}`);
      lines.push(`Approved to Rejected,${summary.approvedToRejected ?? 0}`);
    } else {
      const summary = (targetData as OfficerActivitySummaryResponse).summary || [];
      lines.push('Officer ID,Officer Name,Verifications Count');
      summary.forEach((item) => {
        lines.push(`${item.officerId},"${item.officerName.replace(/"/g, '""')}",${item.verifications}`);
      });
    }

    const csvContent = lines.join('\n');
    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${targetType}_summary_${todayStr}.csv`;
    link.click();
    URL.revokeObjectURL(url);
  };

  const handleDownloadPrevious = async (record: ReportRecord) => {
    const params = dateRangeToParams('30d');
    let rType: ReportType = 'verification';
    if (record.type.toLowerCase().includes('override')) rType = 'override';
    else if (record.type.toLowerCase().includes('officer')) rType = 'officer';

    try {
      let data: GeneratedReport;
      if (rType === 'verification') data = await reportService.verificationSummary(params);
      else if (rType === 'override') data = await reportService.overrideSummary(params);
      else data = await reportService.officerActivity(params);

      handleDownloadCSV(data, rType);
    } catch {
      // Fallback simple download
      const csvContent = `Report Type,${record.type}\nGenerated By,"${record.generatedBy}"\nGenerated Date,"${record.date}"\nStatus,${record.status}\n`;
      const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = `${record.name.toLowerCase().replace(/\s+/g, '_')}.csv`;
      link.click();
      URL.revokeObjectURL(url);
    }
  };

  const filteredPrev = prevReports.filter((r) => {
    const mType = prevType === 'all' || r.type === typeLabel[prevType];
    const mBy = prevBy === 'all' || r.generatedBy === prevBy;
    const recDate = new Date(r.date);
    const now = new Date();
    let mDate = true;
    if (prevDate === '7d') mDate = (now.getTime() - recDate.getTime()) < 7 * 86400000;
    else if (prevDate === '30d') mDate = (now.getTime() - recDate.getTime()) < 30 * 86400000;
    else if (prevDate === '90d') mDate = (now.getTime() - recDate.getTime()) < 90 * 86400000;
    return mType && mBy && mDate;
  });

  const uniqueGenerators = Array.from(new Set(prevReports.map((r) => r.generatedBy)));

  return (
    <div className="space-y-6">
      <div>
        <h2 className="text-base font-semibold text-navy-800">Reports</h2>
        <p className="text-sm text-navy-400 mt-0.5">Generate operational reports and review past reports.</p>
      </div>

      {/* Generate Report card */}
      <div className="card p-6">
        <div className="flex items-center gap-2 mb-1">
          <FileBarChart size={18} className="text-navy-700" />
          <h3 className="text-sm font-semibold text-navy-800">Generate a Report</h3>
        </div>
        <p className="text-xs text-navy-400 mb-5">Select a report type, apply filters, then generate.</p>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          {/* Report type */}
          <div>
            <label className="label flex items-center gap-1.5"><FileText size={12} /> Report Type</label>
            <select
              value={reportType}
              onChange={(e) => { setReportType(e.target.value as ReportType); setGenerated(false); setReportData(null); }}
              className="input"
            >
              <option value="verification">Verification Summary</option>
              <option value="override">Override Summary</option>
              <option value="officer">Officer Activity</option>
            </select>
          </div>

          {/* Officer filter (only for officer activity) */}
          {reportType === 'officer' && (
            <div>
              <label className="label flex items-center gap-1.5"><Filter size={12} /> Officer</label>
              <input
                value={selectedOfficer}
                onChange={(e) => { setSelectedOfficer(e.target.value); setGenerated(false); setReportData(null); }}
                placeholder="Enter officer ID or name"
                className="input"
              />
            </div>
          )}

          {/* Date range */}
          <div className={reportType === 'officer' ? '' : 'md:col-span-2'}>
            <label className="label flex items-center gap-1.5"><Calendar size={12} /> Date Range</label>
            <select
              value={dateRange}
              onChange={(e) => { setDateRange(e.target.value as '7d' | '30d' | '90d' | 'ytd'); setGenerated(false); setReportData(null); }}
              className="input"
            >
              <option value="7d">Last 7 days</option>
              <option value="30d">Last 30 days</option>
              <option value="90d">Last 90 days</option>
              <option value="ytd">Year to date</option>
            </select>
          </div>
        </div>

        {genError && (
          <div className="mt-4 flex items-center gap-2 text-sm text-accent-red bg-accent-red-soft rounded-lg px-3 py-2">
            <AlertCircle size={15} /> {genError}
          </div>
        )}

        <div className="mt-5 flex items-center gap-3">
          <button onClick={handleGenerate} disabled={generating} className="btn-primary disabled:opacity-60">
            {generating ? <><Loader2 size={16} className="animate-spin" /> Generating...</> : <><FileBarChart size={16} /> Generate Report</>}
          </button>
          {generated && (
            <button onClick={() => handleDownloadCSV()} className="btn-success">
              <Download size={16} /> Download CSV
            </button>
          )}
        </div>
      </div>

      {/* Generated report output */}
      {generated && reportData && (
        <div className="card p-6">
          <div className="flex items-center justify-between mb-5">
            <div>
              <div className="flex items-center gap-2">
                <CheckCircle2 size={16} className="text-accent-green" />
                <h3 className="text-sm font-semibold text-navy-800">{typeLabel[reportType]} — Generated</h3>
              </div>
              <p className="text-xs text-navy-400 mt-0.5">
                {reportType === 'officer' && selectedOfficer ? `Officer: ${selectedOfficer} · ` : ''}
                Range: {dateRange === '7d' ? 'Last 7 days' : dateRange === '30d' ? 'Last 30 days' : dateRange === '90d' ? 'Last 90 days' : 'Year to date'}
              </p>
            </div>
            <span className="badge-verified"><CheckCircle2 size={12} /> Ready</span>
          </div>

          <ReportOutput reportType={reportType} data={reportData} />

          <div className="mt-5 pt-4 border-t border-navy-100 flex justify-end">
            <button onClick={() => handleDownloadCSV()} className="btn-success">
              <Download size={16} /> Download CSV
            </button>
          </div>
        </div>
      )}

      {/* Previous reports */}
      <div className="card overflow-hidden">
        <div className="px-5 py-4 border-b border-navy-100 flex flex-col lg:flex-row gap-3 lg:items-center lg:justify-between">
          <h3 className="text-sm font-semibold text-navy-800">Previous Reports</h3>
          <div className="flex flex-wrap items-center gap-3">
            <div className="flex items-center gap-2">
              <Calendar size={15} className="text-navy-400" />
              <select
                value={prevDate}
                onChange={(e) => setPrevDate(e.target.value as 'all' | '7d' | '30d' | '90d')}
                className="rounded-lg border border-navy-200 bg-white px-3 py-2 text-sm text-navy-600 focus:outline-none focus:ring-2 focus:ring-navy-200"
              >
                <option value="all">All Dates</option>
                <option value="7d">Last 7 days</option>
                <option value="30d">Last 30 days</option>
                <option value="90d">Last 90 days</option>
              </select>
            </div>
            <div className="flex items-center gap-2">
              <Filter size={15} className="text-navy-400" />
              <select
                value={prevBy}
                onChange={(e) => setPrevBy(e.target.value)}
                className="rounded-lg border border-navy-200 bg-white px-3 py-2 text-sm text-navy-600 focus:outline-none focus:ring-2 focus:ring-navy-200"
              >
                <option value="all">All Generators</option>
                {uniqueGenerators.map((g) => (
                  <option key={g} value={g}>{g}</option>
                ))}
              </select>
            </div>
            <select
              value={prevType}
              onChange={(e) => setPrevType(e.target.value as 'all' | ReportType)}
              className="rounded-lg border border-navy-200 bg-white px-3 py-2 text-sm text-navy-600 focus:outline-none focus:ring-2 focus:ring-navy-200"
            >
              <option value="all">All Types</option>
              <option value="verification">Verification Summary</option>
              <option value="override">Override Summary</option>
              <option value="officer">Officer Activity</option>
            </select>
          </div>
        </div>

        <div className="overflow-x-auto">
          {prevLoading ? (
            <div className="flex items-center justify-center py-12 text-navy-400">
              <Loader2 size={20} className="animate-spin mr-2" /> Loading...
            </div>
          ) : prevError ? (
            <div className="flex items-center justify-center py-12 text-accent-red">
              <AlertCircle size={18} className="mr-2" /> {prevError}
            </div>
          ) : filteredPrev.length === 0 ? (
            <div className="py-12 text-center text-navy-400 text-sm">No reports match your filters.</div>
          ) : (
            <table className="w-full text-sm">
              <thead className="bg-navy-50">
                <tr>
                  <th className="table-header px-5 py-3">Report ID</th>
                  <th className="table-header px-5 py-3">Report Name</th>
                  <th className="table-header px-5 py-3">Type</th>
                  <th className="table-header px-5 py-3">Generated By</th>
                  <th className="table-header px-5 py-3">Date</th>
                  <th className="table-header px-5 py-3">Status</th>
                  <th className="table-header px-5 py-3 text-right">Action</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-navy-100">
                {filteredPrev.map((r) => (
                  <tr key={r.id} className="hover:bg-navy-50/60 transition-colors">
                    <td className="px-5 py-3 font-mono text-xs text-navy-600">{r.id}</td>
                    <td className="px-5 py-3 font-medium text-navy-800">{r.name}</td>
                    <td className="px-5 py-3"><span className="badge-neutral">{r.type}</span></td>
                    <td className="px-5 py-3 text-navy-600">{r.generatedBy}</td>
                    <td className="px-5 py-3 text-navy-600 whitespace-nowrap">{r.date}</td>
                    <td className="px-5 py-3"><span className="badge-verified"><CheckCircle2 size={12} /> {r.status}</span></td>
                    <td className="px-5 py-3 text-right">
                      <button onClick={() => handleDownloadPrevious(r)} className="text-accent-blue hover:underline text-xs font-medium flex items-center gap-1 ml-auto">
                        <Download size={13} /> Download
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          )}
        </div>
      </div>
    </div>
  );
}

function ReportOutput({ reportType, data }: { reportType: ReportType; data: GeneratedReport }) {
  if (reportType === 'verification') {
    const summary = data.summary as NonNullable<VerificationSummaryResponse['summary']>;
    const chartData = [
      { label: 'Verified', value: summary.verified ?? 0, color: '#16a34a' },
      { label: 'Pending', value: summary.pendingSupervisorReview ?? 0, color: '#d97706' },
      { label: 'Rejected', value: summary.rejected ?? 0, color: '#dc2626' },
    ];
    if (summary.total === 0) return <p className="text-sm text-navy-400">No data for this range.</p>;
    return (
      <div className="grid grid-cols-1 lg:grid-cols-[180px_1fr] gap-6 items-center">
        <DonutChart data={chartData} size={180} />
        <div>
          <h4 className="text-xs font-semibold text-navy-500 uppercase tracking-wide mb-3">Verification Summary</h4>
          <ChartLabels data={chartData} />
          <div className="mt-4 grid grid-cols-3 gap-3 text-center text-xs">
            <StatPill label="Total" value={summary.total} />
            <StatPill label="Verified" value={summary.verified ?? 0} />
            <StatPill label="Pending" value={summary.pendingSupervisorReview ?? 0} />
          </div>
        </div>
      </div>
    );
  }

  if (reportType === 'override') {
    const summary = data.summary as NonNullable<OverrideSummaryResponse['summary']>;
    const chartData = [
      { label: 'Verified', value: summary.approvedToVerified ?? 0, color: '#16a34a' },
      { label: 'Rejected', value: summary.approvedToRejected ?? 0, color: '#dc2626' },
    ];
    if (summary.total === 0) return <p className="text-sm text-navy-400">No data for this range.</p>;
    return (
      <div className="grid grid-cols-1 lg:grid-cols-[180px_1fr] gap-6 items-center">
        <DonutChart data={chartData} size={180} />
        <div>
          <h4 className="text-xs font-semibold text-navy-500 uppercase tracking-wide mb-3">Override Summary</h4>
          <ChartLabels data={chartData} />
          <div className="mt-4 grid grid-cols-3 gap-3 text-center text-xs">
            <StatPill label="Total" value={summary.total} />
            <StatPill label="Verified" value={summary.approvedToVerified ?? 0} />
            <StatPill label="Rejected" value={summary.approvedToRejected ?? 0} />
          </div>
        </div>
      </div>
    );
  }

  const summary = data.summary as OfficerActivitySummaryResponse['summary'];
  if (summary.length === 0) return <p className="text-sm text-navy-400">No data for this range.</p>;
  const chartData = summary.map((entry) => ({
    label: entry.officerName,
    value: entry.verifications,
  }));
  return (
    <div>
      <h4 className="text-xs font-semibold text-navy-500 uppercase tracking-wide mb-3">Officer Activity</h4>
      <BarChart data={chartData} />
      <AxisLabels labels={chartData.map((d) => d.label)} />
    </div>
  );
}

function StatPill({ label, value }: { label: string; value: number }) {
  return (
    <div className="rounded-lg border border-navy-100 bg-navy-50/60 px-3 py-2">
      <div className="text-[10px] uppercase tracking-wide text-navy-400">{label}</div>
      <div className="mt-1 text-sm font-semibold text-navy-800">{value}</div>
    </div>
  );
}
